### PR TITLE
Change type alias to struct

### PR DESCRIPTION
**Pull request by zakaluka**

### CODE REVIEW

**Comment by zakaluka** [comment]
For #29

**Comment by MartinKavik** [comment]
Hi @zakaluka and thanks for the PR.

Please make sure it's compilable, formatted and you should be able to remove some unnecessary Clippy attributes like `#[allow(clippy::trivially_copy_pass_by_ref)]`. 
Thanks!

**Comment by zakaluka** [comment]
I am not able to compile this - trying to figure out how to update the `standback` dependency because it fails to compile on 1.53 nightly.  Will push any additional updates as required.

**Comment by MartinKavik** [comment]
It should work mainly on stable Rust. Nightly isn't required.

**Comment by zakaluka** [comment]
It looks like this is failing on Stable as well.  Apparently `standback` had an issue where the wrong package (feature?) was being referenced: jhpratt/standback#11 .  A new version has been released.

Should I try to use an older version of Rust to try and compile this?

**Comment by zakaluka** [comment]
Oddly enough ... when I build `seed`, it is using `standback 0.2.15`.  However, I am not sure why the quickstart is trying to use `0.2.16`

**Comment by MartinKavik** [comment]
I see. However it looks like they've fixed our older dependency issues and it's compilable for me when I delete `Cargo.lock`. Please delete your `Cargo.lock` and push the new one if it's work, thanks.

**Comment by zakaluka** [comment]
Thanks @MartinKavik .  Cargo.lock is fixed and a test from my fork was successful.

**Comment by MartinKavik** [comment]
Remove please `#[derive(Default)]` from `Model` and replace `Model::default` with
```rust
Model {
    counter: 0
}
```
and we should be ready to go.
Reason: see `Why don't implement Default and other standard traits` block in https://seed-rs.org/0.8.0/model

**Comment by MartinKavik** [comment]
Could you finish it and squash commits when you have time? I would like to merge it and resolve the dependency problem. Thanks!

**Comment by zakaluka** [comment]
Will do.  I will update all 3 areas.

**Comment by zakaluka** [comment]
I need to update the "Model" page on the guide.  I will do that as part of this commit as well.  Will let you know once I've tested it.

**Comment by zakaluka** [comment]
@MartinKavik 4 items have been updated, all linked to #29 in 3 separate pull requests.  2 commit checks are still running (seed and seed-rs.org).  Please let me know if you see any other issues.

**Comment by zakaluka** [comment]
@MartinKavik also, in terms of squashing - I think you have that option when merging the PR.  I tried to squash on seed but I'm not sure it did what you wanted.

**Comment by MartinKavik** [comment]
> @MartinKavik also, in terms of squashing - I think you have that option when merging the PR. I tried to squash on seed but I'm not sure it did what you wanted.

The result should be one force-pushed commit. It's basically [a two-clicks operation](https://www.gitkraken.com/learn/git/git-rebase) if you use something like GitKraken. However I can live with a couple of "weird" commits, I don't want to torture you with too many "administrative tasks". Almost all my repos allow only rebasing.

All PRs now look good if I don't overlook something. I'll merge them once all pipelines pass. Thanks!

**Comment by zakaluka** [comment]
I will try GitKraken next time - thanks for the pointer

**Pull request merged**
